export type PortfolioStatus = "Active" | "Exited" | "Partially Exited";
export type PortfolioFund = "Fund I" | "Fund II" | "Fund III" | "Fund IV";

export type PortfolioCompany = {
  id: string;
  name: string;
  logo?: string;
  fund: PortfolioFund;
  additionalFunds?: PortfolioFund[];
  theme?: string;
  sector: string;
  status: PortfolioStatus;
  tagline?: string;
  description?: string;
  partneredSince?: string;
  entryStage?: string;
  founders?: string[];
  exfinityTeam?: string[];
  linkedinUrl?: string;
  websiteUrl?: string;
};

export type PortfolioWallData = {
  sectionLabel: string;
  companies: PortfolioCompany[];
};

export const updatedPortfolioLogos: Record<string, string> = {
  agshift: "/companies/portfolio-provided/agshift.jpg",
  "ai-palette": "/companies/portfolio-provided/ai-palette.svg",
  akridata: "/companies/portfolio-provided/akridata.png",
  ati: "/companies/featured/ati.png",
  maieutic: "/companies/popup/maieutic-provided.png",
  chara: "/companies/featured/chara.png",
  "raga-ai": "/companies/featured/raga-ai.webp",
  cloudsek: "/companies/featured/cloudsek.png",
  moengage: "/companies/popup/moengage-provided.png",
  pixis: "/companies/featured/pixis.png",
  eccentric: "/companies/popup/eccentric.png",
  awiros: "/companies/portfolio-provided/awiros.png",
  qritive: "/companies/portfolio-provided/qritive.png",
  curefit: "/companies/portfolio-provided/curefit.png",
  "get-edge": "/companies/portfolio-provided/edge-networks.png",
  "hippo-video": "/companies/portfolio-provided/hippo-video.png",
  iqlect: "/companies/portfolio-provided/iqlect.png",
  log9: "/companies/portfolio-provided/log9.jpg",
  "mad-street-den": "/companies/portfolio-provided/mad-street-den.png",
  practically: "/companies/portfolio-provided/practically.png",
  uniken: "/companies/portfolio-provided/uniken.png",
  "neural-garage": "/companies/portfolio-provided/neural-garage.png",
  gridraster: "/companies/portfolio-provided/gridraster.png",
  "resolve-ai": "/companies/portfolio-provided/rezolve-ai.png",
  "skit-ai": "/companies/portfolio-provided/skit-ai.jpg",
  unscript: "/companies/portfolio-provided/unscript.png",
};

// Mirrors the collection shape used by the CMS. Logo remains optional so a
// newly-created entry never breaks the wall while its artwork is being added.
export const portfolioCompanies: PortfolioCompany[] = [
  { id: "agshift", name: "Agshift", fund: "Fund II", theme: "Agri Tech", sector: "DeepTech", status: "Active", tagline: "AgShift designs and manufactures AI-powered machines for quality check and grading of agricultural produce", description: "AgShift is an AI based food technology start-up working on designing the world's most advanced autonomous food inspection system. AgShift's software blends patented Deep Learning models with Computer vision to make food inspections autonomous, consistent and standardized at scale. AgShift is empowering the world's largest food organizations to reduce global food loss and waste. AgShift, Inc. is based out of Silicon Valley, California. The management and advisory team comprises entrepreneurs, technologists and thought leaders with decades of experience in the agriculture and technology industry.", entryStage: "Seed", founders: ["Naveen Tiwary"], exfinityTeam: ["Shailesh Ghorpade"] },
  { id: "ai-palette", name: "Ai Palette", fund: "Fund III", theme: "Food AI", sector: "AI Native Software", status: "Active", tagline: "Artificial Intelligence platform for trends prediction and FMCG product innovation", description: "Ai Palette is on a mission to help CPG brands create their next best-selling product by harnessing the power of artificial intelligence. Its predictive analytics SaaS platform allows product innovation teams to spot trends as they emerge and predict their trajectory in real time. Leading CPG companies use Ai Palette to conceptualize new products, optimize portfolios, localize product lines, strengthen propositions and launch hyper-relevant marketing campaigns. Its proprietary predictive analytics, natural language processing and computer vision technology delivers insights in 16 languages and counting.", entryStage: "Series A", founders: ["Somsubhra Ganchoudri"], exfinityTeam: ["Shailesh Ghorpade", "Arundhati Menon"], websiteUrl: "https://aipalette.com/" },
  { id: "akridata", name: "Akridata", fund: "Fund II", theme: "Deep Tech", sector: "DeepTech", status: "Active", tagline: "Big Data Processing in Edge to core AI Data Pipelines", description: "Akridata leads the way in data-centric AI solutions, transforming the way businesses handle data. Its no-code turnkey platform lets clients process data faster and at a lower cost, intelligently ingest complex data from edge devices, and route and place it across their infrastructure. The platform optimizes cloud footprint, accelerates access for data science teams, visualizes data for outlier identification and image or text search, and provides model-accuracy evaluation to speed improvements while reducing training dataset costs.", founders: ["Kumar Ganapathy", "Vijay Karamchetti", "Sanjay Pichaiah"], exfinityTeam: ["Chinnu Senthilkumar", "Sunith Mandala"] },
  { id: "ati", name: "Ati Robotics", logo: updatedPortfolioLogos.ati, fund: "Fund III", theme: "Robotics", sector: "DeepTech", status: "Active", tagline: "Physical AI for Industrial Material Movement", description: "Ati Robotics builds autonomous mobile robots and an AI-driven material orchestration platform for factories. Its full-stack system combines factory-hardened AMRs, real-time shop-floor data and AI agents to automate and coordinate material movement across complex manufacturing environments.", partneredSince: "2021", entryStage: "Pre-Series A", founders: ["Saurabh Chandra", "Dr. Naveen Arulselvan"], exfinityTeam: ["Chinnu Senthilkumar", "Prachi Singh"], websiteUrl: "https://atirobots.com/" },
  { id: "maieutic", name: "Maieutic", logo: updatedPortfolioLogos.maieutic, fund: "Fund III", theme: "Semiconductors", sector: "DeepTech", status: "Active", tagline: "GenAI copilot for Analog and Mixed-Signal IC design", description: "Maieutic is building a GenAI copilot that helps analog and mixed-signal engineers design chips up to 4x faster. Built on retrieval-augmented generation, it learns from public knowledge, user feedback and each customer's proprietary design data, keeping that data private while getting smarter with every design cycle. It plugs straight into existing EDA toolchains, turning months of manual iteration into AI-guided development.", partneredSince: "2025", entryStage: "Seed", founders: ["Gireesh Rajendran", "Ashish Lachhwani", "Rakesh Kumar"], exfinityTeam: ["Chinnu Senthilkumar", "Sunith Mandala"], websiteUrl: "https://www.maieuticsemi.com/" },
  { id: "chara", name: "Chara", logo: updatedPortfolioLogos.chara, fund: "Fund III", theme: "EV Technology", sector: "DeepTech", status: "Active", tagline: "Design and manufacturing of rare-earth free SynRM based motors.", description: "Chara is reinventing the electric motor, without rare-earth magnets. Its software-controlled synchronous reluctance motors (SynRM) break the dependence on a magnet supply chain dominated by China, and are purpose-built for emerging-market 2/3-wheelers and light commercial vehicles. It is already shipping at scale, a milestone global rivals have yet to reach.", partneredSince: "2022", entryStage: "Series A", founders: ["Bhaktha Keshavachar", "Ravi Prasad", "Mahalingam Koushik"], exfinityTeam: ["Chinnu Senthilkumar", "Sunith Mandala"], websiteUrl: "https://www.chara.co.in/" },
  { id: "raga-ai", name: "RagaAI", logo: updatedPortfolioLogos["raga-ai"], fund: "Fund III", theme: "AI Ops", sector: "AI Native Software", status: "Active", tagline: "Vertical Healthcare AI Agents & AI Reliability Platform", description: "RagaAI builds vertical AI agents for complex enterprise workflows, with an initial focus on healthcare. Its platform combines workflow automation with proprietary AI evaluation, guardrails and data-quality infrastructure, enabling enterprises to deploy and continuously improve reliable AI applications and agents in production.", partneredSince: "2023", entryStage: "Seed", founders: ["Gaurav Agarwal"], exfinityTeam: ["Chinnu Senthilkumar", "Prachi Singh"], websiteUrl: "https://raga.ai/" },
  { id: "awiros", name: "Awiros", fund: "Fund III", theme: "Computer vision", sector: "AI Native Software", status: "Active", tagline: "Hardware-agnostic Platform and App store to run intelligent video AI applications at scale", description: "Awiros is the operating system for video AI. Its hardware-agnostic platform sits between any camera and a marketplace of enterprise-grade apps for safety, surveillance and quality control, letting organisations deploy computer vision 10x faster with 85% less engineering effort. Processing 1,000 hours of video every minute across 60,000 cameras, Awiros is trusted by enterprises such as Pratt & Whitney and Honeywell.", partneredSince: "2022", entryStage: "Series A", founders: ["Vikram Gupta"], exfinityTeam: ["Chinnu Senthilkumar", "Sunith Mandala"] },
  { id: "qritive", name: "Qritive", fund: "Fund III", theme: "AI Pathology", sector: "AI Native Software", status: "Active", tagline: "AI-Powered Digital Pathology", description: "Qritive develops AI-powered digital pathology solutions that help pathologists diagnose cancer faster and more accurately. Its platform analyses digitised pathology images to automate routine workflows, identify abnormalities and improve diagnostic efficiency.", partneredSince: "2022", entryStage: "Series A", founders: ["Bruno Occhipinti", "Kaveh Taghipour"], exfinityTeam: ["Chinnu Senthilkumar", "Prachi Singh"], websiteUrl: "https://qritive.com/" },
  { id: "cloudsek", name: "CloudSEK", logo: updatedPortfolioLogos.cloudsek, fund: "Fund II", theme: "Cybersecurity", sector: "AI Native Software", status: "Active", tagline: "AI-Powered Cyber Threat Intelligence", description: "CloudSEK provides an AI-native cyber intelligence platform that helps enterprises predict and prevent external cyber threats. Its proprietary intelligence layer continuously maps digital assets, identities, credentials, infrastructure and dark-web activity to identify emerging attack paths and vulnerabilities.", partneredSince: "2018", entryStage: "Pre-Series A", founders: ["Rahul Sasi"], exfinityTeam: ["Chinnu Senthilkumar", "Prachi Singh"], websiteUrl: "https://cloudsek.com/" },
  { id: "curefit", name: "Curefit", fund: "Fund I", theme: "Fitness Tech", sector: "B2B Platform", status: "Partially Exited", tagline: "Fitness, Health & Wellness App", description: "At cult.fit, we make group workouts fun, daily food healthy and tasty, mental fitness easy with yoga and meditation, and medical and lifestyle care hassle-free. #BeBetterEveryDay", founders: ["Mukesh Bansal"], exfinityTeam: ["Shailesh Ghorpade"], websiteUrl: "https://www.cult.fit/" },
  { id: "get-edge", name: "Edge Networks", fund: "Fund II", theme: "HR Tech", sector: "AI Native Software", status: "Active", tagline: "AI powered innovative HR tech provider helping organizations simplify their talent acquisition decisions", description: "EDGE is an AI-powered HR technology provider focused on helping organizations solve their toughest talent acquisition and transformation challenges. Its Smart AI EDGE Graph is a knowledge graph created by analysing over 25 million job descriptions and 20 million profiles. EDGE has been ranked among the fastest-growing technology companies in India and recognised by Deloitte, NVIDIA, NASSCOM, Gartner and Google's Launchpad.", founders: ["Arjun Pratap", "Rahul Kulhari"], exfinityTeam: ["Shailesh Ghorpade"], websiteUrl: "https://getedge.ai/" },
  { id: "hippo-video", name: "Hippo Video", fund: "Fund II", theme: "Marketing Tech", sector: "AI Native Software", status: "Active", tagline: "Personalised Videos for enterprise sales, marketing & customer success teams to improve conversion rates", description: "Hippo Video is an interactive video customer experience platform for B2B sales teams. Sales representatives can record, send and track personalized videos to humanize outreach, build relationships, improve response rates and close deals faster.", founders: ["Karthi Mariappan", "Srinivasan Santhana Krishnan", "Nilamchand Jain"], exfinityTeam: ["Shailesh Ghorpade"], websiteUrl: "https://www.hippovideo.io/" },
  { id: "iqlect", name: "IQLECT", fund: "Fund II", theme: "Deep Tech", sector: "DeepTech", status: "Active", tagline: "NoSQL Database for real-time predictive operations intelligence", founders: ["Sachin Sinha"], exfinityTeam: ["Shailesh Ghorpade", "Sunith Mandala"], websiteUrl: "https://bangdb.com/" },
  { id: "locus", name: "Locus", logo: "/companies/popup/locus.png", fund: "Fund II", theme: "Logistics Tech", sector: "B2B Platform", status: "Exited", tagline: "End-to-end logistics management platform to optimise the last-mile of delivery", description: "Locus is a technology company solving one of the most challenging global supply-chain problems: last-mile logistics. Its order-to-delivery dispatch management platform helps enterprises transform last-mile operations into growth centers through advanced optimization algorithms and intuitive workflow automation. Founded in 2015, Locus has helped customers including Unilever, Nestle, Bukalapak, The Tata Group and BlueDart execute 650 million deliveries across 30+ countries, save $200 million in transit costs and offset 70 million kilograms of CO2 emissions.", founders: ["Nishith Rastogi", "Geet Garg"], exfinityTeam: ["Shailesh Ghorpade"], websiteUrl: "https://locus.sh/" },
  { id: "log9", name: "LOG9", fund: "Fund II", theme: "Battery Tech", sector: "DeepTech", status: "Active", tagline: "Efficient EV and Storage Battery solution using Graphene nano-material", description: "Log9 is furthering India's transition to a clean and sustainable mobility and energy-storage ecosystem with batteries that can be charged 9x faster, last 9x longer, and offer 9x higher performance and safety. The deep-tech company holds in-house competencies spanning electrode materials, cell fabrication and battery packs, supported by a portfolio of more than 80 patents.", founders: ["Akshay Singhal", "Pankaj Sharma", "Kartik Hajela"], exfinityTeam: ["Chinnu Senthilkumar", "Sunith Mandala"], websiteUrl: "https://www.log9materials.com/" },
  { id: "mad-street-den", name: "Mad Street Den", fund: "Fund I", additionalFunds: ["Fund II"], theme: "SaaS", sector: "AI Native Software", status: "Partially Exited", tagline: "Enterprise AI company that help businesses become AI native", description: "Mad Street Den is a computer vision and artificial intelligence company founded to make people around the globe AI natives. Its first vertical, Vue.ai, brings intelligent retail automation to traditional stores and online retail businesses through image and video recognition. Following the growth of its retail platform, the company has expanded into healthcare, education, finance and other verticals.", founders: ["Ashwini Asokan", "Anand Chandrasekaran"], exfinityTeam: ["Shailesh Ghorpade"], websiteUrl: "https://www.madstreetden.com/" },
  { id: "moengage", name: "MoEngage", logo: updatedPortfolioLogos.moengage, fund: "Fund I", theme: "SaaS", sector: "AI Native Software", status: "Exited", tagline: "Customer engagement & campaign management platform", description: "MoEngage is an insights-led customer engagement platform for marketers and product owners. It helps businesses analyze customer behavior and engage users with personalized communication across web, mobile and email. Its full-stack solution combines customer analytics, AI-powered journey orchestration and personalization in one dashboard, serving Fortune 500 enterprises and mobile-first brands worldwide.", founders: ["Raviteja Dodda", "Yashwanth Kumar"], exfinityTeam: ["Shailesh Ghorpade"], websiteUrl: "https://www.moengage.com/" },
  { id: "practically", name: "Practically", fund: "Fund II", theme: "Edu Tech", sector: "B2B Platform", status: "Active", tagline: "Interactive & Experiential AR/VR learning platform using AI-based Learning & Assessment", description: "Practically is an experiential learning app designed to make learning immersive for students in classes 6–12. It offers more than 3,000 3D videos, 1,000 AR experiences and simulations, live classes, dedicated mentor support, study plans, test preparation, coding courses and an AI Study Buddy. Its B2B2C school solution also gives schools and teachers access to the Practically teacher app.", founders: ["Subbarao Siddabattula", "Charu Noheria", "Ilangovel Thulasimani"], exfinityTeam: ["Sunith Mandala"] },
  { id: "uniken", name: "Uniken", fund: "Fund II", theme: "SaaS", sector: "AI Native Software", status: "Active", tagline: "Military grade end point threat detection & authentication cybersecurity company", description: "Uniken creates certainty in identity and security while delivering customer experiences through its REL-ID security platform. REL-ID secures the customer journey end-to-end—from devices, applications and network connections to customer authentication, transaction verification and digital signing—helping organizations drive fraud toward zero while keeping interactions fast and frictionless.", founders: ["Bimal Gandhi", "Nishant Kaushik"], exfinityTeam: ["Shailesh Ghorpade"] },
  { id: "pixis", name: "Pixis", logo: updatedPortfolioLogos.pixis, fund: "Fund II", theme: "Marketing-Tech", sector: "AI Native Software", status: "Active", tagline: "Autonomous AI agents for Marketing workflows", description: "Pixis builds an AI-native marketing platform that replaces manual campaign operations with autonomous agents for global brands. Its specialised agents are trained on billions of live ad-account data points, and brands direct them through a single plain-language Manager Agent. Together they run paid and organic growth across campaign performance, creative generation and AI-search visibility.", partneredSince: "2017", entryStage: "Seed", founders: ["Shubham Mishra", "Vrushali Prasade", "Hari Valiayth"], exfinityTeam: ["Chinnu Senthilkumar", "Nitin Lalwani"] },
  { id: "neural-garage", name: "NeuralGarage", fund: "Fund III", theme: "GenerativeAI", sector: "AI Native Software", status: "Active", tagline: "Enterprise software to ensure lip-syncing of high-resolution video content", description: "NeuralGarage makes dubbed content look as natural as it sounds. Its patented visual-dubbing technology generates lip and jaw movements that sync with any audio track, removing the out-of-sync feel when films and OTT shows travel across languages. Supporting 17+ languages and powered by high-quality 4K footage, it brings truly seamless localisation to global content.", partneredSince: "2022", entryStage: "Seed", founders: ["Mandar Natekar", "Subhabrata Debnath", "Subhashish Saha", "Anjan Banerjee"], exfinityTeam: ["Shailesh Ghorpade", "Sunith Mandala"], websiteUrl: "https://visualdub.ai/" },
  { id: "eccentric", name: "Eccentric", logo: updatedPortfolioLogos.eccentric, fund: "Fund III", theme: "Automotive", sector: "AI Native Software", status: "Active", tagline: "Automotive 3D & GenAI Visualisation Platform", description: "Eccentric provides an automotive-first visualisation platform combining proprietary real-time 3D technology with GenAI. Its One3D platform transforms OEM CAD assets into accurate, interactive digital vehicle experiences across websites, dealerships and other customer touchpoints.", partneredSince: "2025", entryStage: "Pre-Series A", founders: ["Varun Shah", "Gaurav Rane"], exfinityTeam: ["Shailesh Ghorpade", "Prachi Singh"], websiteUrl: "https://weareeccentric.com/" },
  { id: "autoverse", name: "Autoverse", logo: "/companies/popup/autoverse.png", fund: "Fund III", theme: "B2B autocomponents marketplace", sector: "B2B Platform", status: "Active", tagline: "On demand delivery of Auto parts for multi brand garages", description: "Autoverse is building a faster, more transparent supply chain for the auto aftermarket, delivering genuine parts on demand to multi-brand garages. Its AI platform maps parts to specific vehicles, and an AI-powered chatbot helps garage owners find the right part first time, tackling an industry-wide 20% error rate.", partneredSince: "2023", entryStage: "Seed", founders: ["Mihir Mohan Krishnakumar R", "Shiv Soni"], exfinityTeam: ["Shailesh Ghorpade", "Sunith Mandala"], websiteUrl: "https://www.autoversemobility.in/" },
  { id: "credilio", name: "Credilio", logo: "/companies/popup/credilio.png", fund: "Fund III", theme: "Fintech Platform", sector: "B2B Platform", status: "Active", tagline: "AI-Powered Credit Distribution & Secured Card Issuance", description: "Credilio builds AI-powered credit distribution infrastructure that unifies banks, NBFCs and DSA networks across India on a single platform. Its intelligence layer drives real-time product matching, instant eligibility checks and multi-lender workflows, turning fragmented offline sourcing into high-conversion digital journeys. Its co-branded secured credit cards extend formal credit to new-to-credit consumers.", partneredSince: "2022", entryStage: "Pre-Series A", founders: ["Aditya Gupt", "Sandeep Ghule", "Anand Kapadia", "Manish Sinha"], exfinityTeam: ["Shailesh Ghorpade", "Nitin Lalwani"] },
  { id: "gridraster", name: "GridRaster", fund: "Fund II", theme: "Defense Tech", sector: "DeepTech", status: "Active", tagline: "Spatial AI Platform for Industrial & Defense Operations", description: "GridRaster provides an AI-powered spatial computing platform for complex industrial and defense workflows. Its technology combines XR, computer vision and AI to enable digital work instructions, remote assistance, inspection, training, robotic repair and other modernization workflows across aerospace, manufacturing and U.S. defense depots.", partneredSince: "2017", entryStage: "Seed", founders: ["Rishi Ranjan", "Dijam Panigrahi", "Bhaskar Banerjee"], exfinityTeam: ["Chinnu Senthilkumar", "Prachi Singh"], websiteUrl: "https://gridraster.com/" },
  { id: "kinara", name: "Kinara AI", logo: "/companies/popup/kinara-provided.png", fund: "Fund II", theme: "Semiconductor", sector: "DeepTech", status: "Exited", tagline: "Ultra Low Power Programmable AI Silicon Chip for High Performance Edge applications", description: "Kinara built ultra-low-power, programmable AI inference chips to bring high-performance AI to the edge, without the cost, power draw or privacy trade-offs of GPUs. Its patented Ara-1 and Ara-2 accelerators are in mass production, powering laptops, smart cameras and self-checkout stores around the world. In February 2025, Kinara was acquired by NXP Semiconductors in an all-cash deal at a $307M valuation.", partneredSince: "2019", entryStage: "Series A", exfinityTeam: ["Chinnu Senthilkumar", "Sunith Mandala"] },
  { id: "optimized-electrotech", name: "Optimised Electrotech", logo: "/companies/popup/optimized-electrotech-provided.png", fund: "Fund III", theme: "Defence Tech", sector: "DeepTech", status: "Active", tagline: "Electro Optic Surveillance", description: "Optimized Electrotech builds AI-powered electro-optic systems using multispectral infrared sensors (SWIR, MWIR, LWIR) for long-range, all-weather surveillance. Defence and security agencies use them for real-time situational awareness across border, counter-drone and critical infrastructure missions.", partneredSince: "2026", entryStage: "Series B", founders: ["Sandeep Shah", "Dharin Shah"], exfinityTeam: ["Chinnu Senthilkumar", "Nitin Lalwani"] },
  { id: "resolve-ai", name: "Rezolve AI", fund: "Fund III", theme: "AI powered ITSM", sector: "AI Native Software", status: "Active", tagline: "AI to auto-resolve IT and HR support employee issues", description: "Rezolve.ai brings instant, AI-powered employee support into the tools teams already use: Microsoft Teams, Slack or an embeddable AI agent. It auto-resolves IT and HR requests with a 70%+ self-service rate and 45%+ auto-resolution, responding in about 10 seconds versus 6+ hours for human service desks, all at roughly 30% lower cost than existing solutions.", partneredSince: "2023", entryStage: "Series A", founders: ["Saurabh Kumar", "Manish Sharma", "Udaya Reddy"], exfinityTeam: ["Chinnu Senthilkumar", "Sunith Mandala"], websiteUrl: "https://www.rezolve.ai/" },
  { id: "skit-ai", name: "SkitAI", fund: "Fund III", theme: "Conversational AI", sector: "B2B Platform", status: "Active", tagline: "AI Native Services", description: "Skit.ai builds an AI-native, full-stack debt collections platform for lenders and debt buyers in regulated post-charge-off recovery. It combines data modelling, AI agents, humans and compliance, learning continuously from 125M+ proprietary debtor interactions.", exfinityTeam: ["Rajiv Kuchhal", "Nitin Lalwani"] },
  { id: "str8bat", name: "Str8bat", logo: "/companies/popup/str8bat-provided.png", fund: "Fund III", theme: "AI Analytics", sector: "DeepTech", status: "Active", tagline: "Physical AI for Human Motion & Sports Performance", description: "Str8bat builds a sport-agnostic Physical AI platform that turns human movement into structured, machine-readable performance data. Its proprietary sensor-to-AI stack measures motion directly, without cameras or body markers, and generates leading indicators such as bat speed, shot timing and impact quality. Proven in elite cricket, the platform extends to running, golf and broadcast analytics.", partneredSince: "2024", entryStage: "Pre-Series A", founders: ["Gagan Daga", "Rahul Nagar", "Madhu Sudan"], exfinityTeam: ["Shailesh Ghorpade", "Nitin Lalwani"] },
  { id: "unscript", name: "Unscript", fund: "Fund III", theme: "GenAI", sector: "AI Native Software", status: "Active", tagline: "AI-Powered Enterprise Video Creation", description: "Unscript is a generative AI platform that enables enterprises and brands to create professional video content at scale from text. Its platform supports AI avatars, multilingual dubbing and translation, personalized video campaigns, and visual content generation, helping marketing and enterprise teams reduce production time and cost.", partneredSince: "2022", entryStage: "Seed", founders: ["Ritwika Chowdhury"], exfinityTeam: ["Chinnu Senthilkumar", "Prachi Singh"], websiteUrl: "https://unscript.ai/" },
  { id: "zyla-health", name: "Zyla", logo: "/companies/popup/zyla.png", fund: "Fund III", theme: "Healthtech", sector: "B2B Platform", status: "Active", tagline: "Healthcare platform to help insurance / corporate firms reduce insurance claims", description: "Zyla is a health-tech platform that delivers personalised health guidance to keep people healthier, and claims lower. Insurers use it to reduce claim rates, corporates to strengthen employee wellbeing and benefits, and pharma companies to build their medical brands and drive treatment adherence. Backed by extensive R&D with proven medical and commercial outcomes, Zyla's insurer-first model wins where B2C health apps have struggled.", partneredSince: "2023", entryStage: "Series A", founders: ["Khushboo Aggarwal"], exfinityTeam: ["Shailesh Ghorpade", "Sunith Mandala"], websiteUrl: "https://zyla.in/" },
];

for (const company of portfolioCompanies) {
  company.logo ??= updatedPortfolioLogos[company.id];
}

export const fallbackPortfolioWall: PortfolioWallData = {
  sectionLabel: "Our Portfolio",
  companies: portfolioCompanies,
};
